### ISSUE TITLE
Missing tags mean the package cannot be installed in a working condition

### ISSUE THREAD

**Issue by ThisIsJustARandomGuy** [dachcom-digital/pimcore-dynamic-search-index-provider-elasticsearch#2]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | maybe?
| RFC?             | no

Unfortunately, there are no tags for this package. This means that only dev-master or a specific commit can be required using composer. It seems like there are no working combinations of version constraints. Installing the following versions results in an error message. I tried various requiring specific commits of the elasticsearch provider but none of them seem to work together with v0.7.

```JSON
"require": {
    "dachcom-digital/dynamic-search": "^0.7",
    "dachcom-digital/dynamic-search-data-provider-trinity": "^0.7",
    "dachcom-digital/dynamic-search-index-provider-elasticsearch": "dev-master"
}
```

`Fatal error: Cannot make non static method DynamicSearchBundle\OutputChannel\OutputChannelInterface::configureOptions() static in class DsElasticSearchBundle\OutputChannel\SearchOutputChannel in /var/www/vendor/dachcom-digital/dynamic-search-index-provider-elasticsearch/src/DsElasticSearchBundle/OutputChannel/SearchOutputChannel.php on line 46`

**Comment by solverat** [comment]
try this:

```json
"require": {
        "dachcom-digital/dynamic-search": "1.0.x-dev as 0.7",
        "dachcom-digital/dynamic-search-data-provider-trinity": "1.0.x-dev as 0.7",
        "dachcom-digital/dynamic-search-index-provider-elasticsearch": "1.0.x-dev as 0.7",
}
```

Please note that there is no final release yet and breaking changes are still allowed. However, we're planing releasing v1 the next weeks.
